// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Default packages for conda environments.
 */
export type CondaDefaults = { default_packages: Array<string>, };
