// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Python environment type for dependency management.
 *
 * Unknown values are captured in the `Other` variant so they survive
 * serialization round-trips across branches that add new env types.
 */
export type PythonEnvType = "uv" | "conda" | (string & {});
