// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Python environment type for dependency management
 */
export type PythonEnvType = "uv" | "conda";
