// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported notebook runtime environments.
 *
 * Unknown values are captured in the `Other` variant so they survive
 * serialization round-trips across branches that add new runtimes.
 */
export type Runtime = "python" | "deno" | (string & {});
