// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CondaDefaults } from "./CondaDefaults";
import type { ThemeMode } from "./ThemeMode";
import type { UvDefaults } from "./UvDefaults";

/**
 * Snapshot of all synced settings.
 */
export type SyncedSettings = {
  theme: ThemeMode;
  default_runtime: string;
  default_python_env: string;
  uv: UvDefaults;
  conda: CondaDefaults;
};
