// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CondaDefaults } from "./CondaDefaults";
import type { PythonEnvType } from "./PythonEnvType";
import type { Runtime } from "./Runtime";
import type { ThemeMode } from "./ThemeMode";
import type { UvDefaults } from "./UvDefaults";

/**
 * Snapshot of all synced settings.
 */
export type SyncedSettings = { 
/**
 * UI theme
 */
theme: ThemeMode, 
/**
 * Default runtime for new notebooks
 */
default_runtime: Runtime, 
/**
 * Default Python environment type (uv or conda)
 */
default_python_env: PythonEnvType, 
/**
 * UV environment defaults
 */
uv: UvDefaults, 
/**
 * Conda environment defaults
 */
conda: CondaDefaults, };
